name:                EvoAlg
version:             0.1.0.0
github:              "github.com/balacij/EvoAlg"
license:             BSD-3-Clause
author:              "Jason Balaci"
maintainer:          "jason@balaci.me"
copyright:           "2024 Jason Balaci"
extra-source-files:  []
language: Haskell2010
default-extensions:
- OverloadedStrings
- StrictData
- LambdaCase
- InstanceSigs

description: Please see the README on GitHub at <https://github.com/balacij/EvoAlg>

dependencies:
- base >= 4.7 && < 5
- random
- containers
- parsec
- parallel
- deepseq
- text
- vector
- vector-algorithms
- megaparsec
- parser-combinators
- cassava
- bytestring
- directory
- filepath

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -Wno-orphans
- -Wno-missing-export-lists

library:
  source-dirs: lib

executables:
  ge-ast-exe:
    main:                GE.MainAST
    source-dirs:         app
    dependencies:
    - EvoAlg
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N6
    - -O2

  ge-cst-exe:
    main:                GE.MainCST
    source-dirs:         app
    dependencies:
    - EvoAlg
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N6
    - -O2

  gp-exe:
    main:                GP.Main
    source-dirs:         app
    dependencies:
    - EvoAlg
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N6
    - -O2
